name: milk_minder
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  
  flutter:
    sdk: flutter
  fl_chart: ^0.65.0  
  flutter_svg: ^2.0.16
  google_fonts: ^6.2.1
  pdf: ^3.11.1
  printing: ^5.13.4
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.3
  image_picker: ^1.1.2
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.1
  provider: ^6.1.2
  font_awesome_flutter: ^10.8.0
  flutter_localization: ^0.3.0
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

assets:
  - assets/